version: 0.1.6.{build}

platform: Any CPU
configuration: Release

before_build:
  - nuget restore Source\Code\ProjectPlugins.sln

build:
  project: Source\Code\ProjectPlugins.sln
  verbosity: minimal
  publish_nuget: true
